name: ðŸƒ Windows

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]
        operating-system: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Create cache folder if doesn't already exist
        run: |
          mkdir -p ~/conda_pkgs_dir
          echo "CONDA_PKGS_DIRS=$HOME/conda_pkgs_dir" >> $GITHUB_ENV

      - name: Cache conda
        uses: actions/cache@v1
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-env-${{ hashFiles('etc/conda-win-64.lock') }}
          restore-keys: |
            ${{ runner.os }}-conda-env-

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/Scripts >> $GITHUB_PATH
          $CONDA/Scripts/conda config --set use_only_tar_bz2 true

      - name: Install dependencies
        run: |
          conda create --name testenv --file etc/conda-win-64.lock

      - name: Test explicit env
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate testenv
          conda info
          conda list
